// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: proto/demo/v1/demo.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DemoService_GetUser_FullMethodName           = "/demo.v1.DemoService/GetUser"
	DemoService_LogEvent_FullMethodName          = "/demo.v1.DemoService/LogEvent"
	DemoService_ListUsers_FullMethodName         = "/demo.v1.DemoService/ListUsers"
	DemoService_SubscribeToEvents_FullMethodName = "/demo.v1.DemoService/SubscribeToEvents"
	DemoService_UploadData_FullMethodName        = "/demo.v1.DemoService/UploadData"
	DemoService_ProcessBatch_FullMethodName      = "/demo.v1.DemoService/ProcessBatch"
	DemoService_Chat_FullMethodName              = "/demo.v1.DemoService/Chat"
	DemoService_Interactive_FullMethodName       = "/demo.v1.DemoService/Interactive"
)

// DemoServiceClient is the client API for DemoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DemoService demonstrates all 4 core gRPC communication patterns:
// 1. Unary RPC (Request-Response)
// 2. Server Streaming RPC
// 3. Client Streaming RPC
// 4. Bidirectional Streaming RPC
type DemoServiceClient interface {
	// ============================================================================
	// 1. UNARY RPC (Request-Response)
	// ============================================================================
	// Pattern: Client sends one request, server sends one response
	// Use Cases: REST-like APIs, CRUD operations, authentication, simple queries
	// Characteristics: Simplest pattern, blocking, single request/response pair
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	// Fire-and-Forget pattern (built on Unary with empty response)
	// Use Cases: Logging, metrics, notifications
	LogEvent(ctx context.Context, in *LogEventRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ============================================================================
	// 2. SERVER STREAMING RPC
	// ============================================================================
	// Pattern: Client sends one request, server sends stream of responses
	// Use Cases: Paginated results, large downloads, real-time updates, events
	// Characteristics: Server keeps connection open, sends multiple messages
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[User], error)
	// Event streaming pattern (built on Server Streaming)
	// Use Cases: Real-time notifications, pub/sub, live updates
	SubscribeToEvents(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	// ============================================================================
	// 3. CLIENT STREAMING RPC
	// ============================================================================
	// Pattern: Client sends stream of requests, server sends one response
	// Use Cases: File uploads, batch operations, data ingestion, aggregation
	// Characteristics: Client sends multiple messages, server waits for all
	UploadData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DataChunk, UploadResponse], error)
	// Batch processing pattern (built on Client Streaming)
	// Use Cases: Bulk operations, batch imports, aggregation
	ProcessBatch(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[BatchItem, BatchResult], error)
	// ============================================================================
	// 4. BIDIRECTIONAL STREAMING RPC
	// ============================================================================
	// Pattern: Both client and server send streams independently
	// Use Cases: Chat, gaming, real-time collaboration, WebSocket-like communication
	// Characteristics: Full duplex, independent read/write streams, most flexible
	Chat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChatMessage, ChatMessage], error)
	// Ping-Pong pattern (built on Bidirectional with alternating messages)
	// Use Cases: Turn-based games, interactive shells, conversational AI
	Interactive(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Request, Response], error)
}

type demoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDemoServiceClient(cc grpc.ClientConnInterface) DemoServiceClient {
	return &demoServiceClient{cc}
}

func (c *demoServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, DemoService_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *demoServiceClient) LogEvent(ctx context.Context, in *LogEventRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DemoService_LogEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *demoServiceClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[User], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DemoService_ServiceDesc.Streams[0], DemoService_ListUsers_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListUsersRequest, User]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DemoService_ListUsersClient = grpc.ServerStreamingClient[User]

func (c *demoServiceClient) SubscribeToEvents(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DemoService_ServiceDesc.Streams[1], DemoService_SubscribeToEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DemoService_SubscribeToEventsClient = grpc.ServerStreamingClient[Event]

func (c *demoServiceClient) UploadData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DataChunk, UploadResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DemoService_ServiceDesc.Streams[2], DemoService_UploadData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DataChunk, UploadResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DemoService_UploadDataClient = grpc.ClientStreamingClient[DataChunk, UploadResponse]

func (c *demoServiceClient) ProcessBatch(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[BatchItem, BatchResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DemoService_ServiceDesc.Streams[3], DemoService_ProcessBatch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BatchItem, BatchResult]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DemoService_ProcessBatchClient = grpc.ClientStreamingClient[BatchItem, BatchResult]

func (c *demoServiceClient) Chat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChatMessage, ChatMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DemoService_ServiceDesc.Streams[4], DemoService_Chat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatMessage, ChatMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DemoService_ChatClient = grpc.BidiStreamingClient[ChatMessage, ChatMessage]

func (c *demoServiceClient) Interactive(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Request, Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DemoService_ServiceDesc.Streams[5], DemoService_Interactive_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Request, Response]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DemoService_InteractiveClient = grpc.BidiStreamingClient[Request, Response]

// DemoServiceServer is the server API for DemoService service.
// All implementations must embed UnimplementedDemoServiceServer
// for forward compatibility.
//
// DemoService demonstrates all 4 core gRPC communication patterns:
// 1. Unary RPC (Request-Response)
// 2. Server Streaming RPC
// 3. Client Streaming RPC
// 4. Bidirectional Streaming RPC
type DemoServiceServer interface {
	// ============================================================================
	// 1. UNARY RPC (Request-Response)
	// ============================================================================
	// Pattern: Client sends one request, server sends one response
	// Use Cases: REST-like APIs, CRUD operations, authentication, simple queries
	// Characteristics: Simplest pattern, blocking, single request/response pair
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	// Fire-and-Forget pattern (built on Unary with empty response)
	// Use Cases: Logging, metrics, notifications
	LogEvent(context.Context, *LogEventRequest) (*emptypb.Empty, error)
	// ============================================================================
	// 2. SERVER STREAMING RPC
	// ============================================================================
	// Pattern: Client sends one request, server sends stream of responses
	// Use Cases: Paginated results, large downloads, real-time updates, events
	// Characteristics: Server keeps connection open, sends multiple messages
	ListUsers(*ListUsersRequest, grpc.ServerStreamingServer[User]) error
	// Event streaming pattern (built on Server Streaming)
	// Use Cases: Real-time notifications, pub/sub, live updates
	SubscribeToEvents(*SubscribeRequest, grpc.ServerStreamingServer[Event]) error
	// ============================================================================
	// 3. CLIENT STREAMING RPC
	// ============================================================================
	// Pattern: Client sends stream of requests, server sends one response
	// Use Cases: File uploads, batch operations, data ingestion, aggregation
	// Characteristics: Client sends multiple messages, server waits for all
	UploadData(grpc.ClientStreamingServer[DataChunk, UploadResponse]) error
	// Batch processing pattern (built on Client Streaming)
	// Use Cases: Bulk operations, batch imports, aggregation
	ProcessBatch(grpc.ClientStreamingServer[BatchItem, BatchResult]) error
	// ============================================================================
	// 4. BIDIRECTIONAL STREAMING RPC
	// ============================================================================
	// Pattern: Both client and server send streams independently
	// Use Cases: Chat, gaming, real-time collaboration, WebSocket-like communication
	// Characteristics: Full duplex, independent read/write streams, most flexible
	Chat(grpc.BidiStreamingServer[ChatMessage, ChatMessage]) error
	// Ping-Pong pattern (built on Bidirectional with alternating messages)
	// Use Cases: Turn-based games, interactive shells, conversational AI
	Interactive(grpc.BidiStreamingServer[Request, Response]) error
	mustEmbedUnimplementedDemoServiceServer()
}

// UnimplementedDemoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDemoServiceServer struct{}

func (UnimplementedDemoServiceServer) GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedDemoServiceServer) LogEvent(context.Context, *LogEventRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method LogEvent not implemented")
}
func (UnimplementedDemoServiceServer) ListUsers(*ListUsersRequest, grpc.ServerStreamingServer[User]) error {
	return status.Error(codes.Unimplemented, "method ListUsers not implemented")
}
func (UnimplementedDemoServiceServer) SubscribeToEvents(*SubscribeRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method SubscribeToEvents not implemented")
}
func (UnimplementedDemoServiceServer) UploadData(grpc.ClientStreamingServer[DataChunk, UploadResponse]) error {
	return status.Error(codes.Unimplemented, "method UploadData not implemented")
}
func (UnimplementedDemoServiceServer) ProcessBatch(grpc.ClientStreamingServer[BatchItem, BatchResult]) error {
	return status.Error(codes.Unimplemented, "method ProcessBatch not implemented")
}
func (UnimplementedDemoServiceServer) Chat(grpc.BidiStreamingServer[ChatMessage, ChatMessage]) error {
	return status.Error(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedDemoServiceServer) Interactive(grpc.BidiStreamingServer[Request, Response]) error {
	return status.Error(codes.Unimplemented, "method Interactive not implemented")
}
func (UnimplementedDemoServiceServer) mustEmbedUnimplementedDemoServiceServer() {}
func (UnimplementedDemoServiceServer) testEmbeddedByValue()                     {}

// UnsafeDemoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DemoServiceServer will
// result in compilation errors.
type UnsafeDemoServiceServer interface {
	mustEmbedUnimplementedDemoServiceServer()
}

func RegisterDemoServiceServer(s grpc.ServiceRegistrar, srv DemoServiceServer) {
	// If the following call panics, it indicates UnimplementedDemoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DemoService_ServiceDesc, srv)
}

func _DemoService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemoServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DemoService_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemoServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DemoService_LogEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemoServiceServer).LogEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DemoService_LogEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemoServiceServer).LogEvent(ctx, req.(*LogEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DemoService_ListUsers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListUsersRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DemoServiceServer).ListUsers(m, &grpc.GenericServerStream[ListUsersRequest, User]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DemoService_ListUsersServer = grpc.ServerStreamingServer[User]

func _DemoService_SubscribeToEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DemoServiceServer).SubscribeToEvents(m, &grpc.GenericServerStream[SubscribeRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DemoService_SubscribeToEventsServer = grpc.ServerStreamingServer[Event]

func _DemoService_UploadData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DemoServiceServer).UploadData(&grpc.GenericServerStream[DataChunk, UploadResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DemoService_UploadDataServer = grpc.ClientStreamingServer[DataChunk, UploadResponse]

func _DemoService_ProcessBatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DemoServiceServer).ProcessBatch(&grpc.GenericServerStream[BatchItem, BatchResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DemoService_ProcessBatchServer = grpc.ClientStreamingServer[BatchItem, BatchResult]

func _DemoService_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DemoServiceServer).Chat(&grpc.GenericServerStream[ChatMessage, ChatMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DemoService_ChatServer = grpc.BidiStreamingServer[ChatMessage, ChatMessage]

func _DemoService_Interactive_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DemoServiceServer).Interactive(&grpc.GenericServerStream[Request, Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DemoService_InteractiveServer = grpc.BidiStreamingServer[Request, Response]

// DemoService_ServiceDesc is the grpc.ServiceDesc for DemoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DemoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "demo.v1.DemoService",
	HandlerType: (*DemoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _DemoService_GetUser_Handler,
		},
		{
			MethodName: "LogEvent",
			Handler:    _DemoService_LogEvent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListUsers",
			Handler:       _DemoService_ListUsers_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeToEvents",
			Handler:       _DemoService_SubscribeToEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UploadData",
			Handler:       _DemoService_UploadData_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ProcessBatch",
			Handler:       _DemoService_ProcessBatch_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Chat",
			Handler:       _DemoService_Chat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Interactive",
			Handler:       _DemoService_Interactive_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/demo/v1/demo.proto",
}
